vscode:
    extensions:
        - davidanson.vscode-markdownlint@0.38.0:MCcSWKBmgWaXjm6m9AHE2Q==
        - esbenp.prettier-vscode@5.9.1:iOd2sieSR48o6zF3hElemQ==
        - timonwong.shellcheck@0.13.1:GSm2emQo+yncGhLCePxqOA==
