name: Push Image

on:
    push:
        branches: main
    release:
        types: [published, edited]

jobs:
    main:
        runs-on: ubuntu-latest
        env:
            buildx_platforms: linux/amd64
        steps:
            - name: Set up QEMU
              id: qemu
              uses: docker/setup-qemu-action@v2
              with:
                  platforms: all
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Cache Docker layers
              uses: actions/cache@v3
              env:
                  cache-name: docker-cache
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./docker/Dockerfile') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Build and push unstable
              id: docker_build
              uses: docker/build-push-action@v4
              with:
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache
                  platforms: ${{ env.buildx_platforms }}
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/textidote:unstable
            - name: Determine release tag name
              if: ${{ github.event_name == 'release' }}
              id: vars
              run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
            - name: Build and push release
              if: ${{ github.event_name == 'release' }}
              uses: docker/build-push-action@v4
              with:
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache
                  platforms: ${{ env.buildx_platforms }}
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/textidote:${{steps.vars.outputs.tag}},
                      ${{ secrets.DOCKERHUB_USERNAME }}/textidote:latest
            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
            - name: Checkout Git repository
              uses: actions/checkout@v3
            - name: Update Docker Hub description
              uses: peter-evans/dockerhub-description@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
                  repository: gokhlayeh/textidote
                  readme-filepath: doc/docker/README.md
