name: Code Quality

on: [push, pull_request]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Set up Python environment
              uses: actions/setup-python@v2
            - name: Run pre-commit checks
              uses: pre-commit/action@v2.0.3
