name: self-check

on: [push, pull_request]

jobs:
    self-check:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Lint fine.tex
              uses: ./
              with:
                  root_file: fine.tex
                  working_directory: test/
                  threshold_error: 0
            - name: Lint bad.tex with no threshold set
              uses: ./
              with:
                  root_file: bad.tex
                  working_directory: test/
            - name: Lint bad.tex with threshold set to known warnings
              uses: ./
              with:
                  root_file: bad.tex
                  working_directory: test/
                  threshold_error: 21
            - name: Lint and spell-check fine.tex
              uses: ./
              with:
                  root_file: fine.tex
                  working_directory: test/
                  args: --check en
                  threshold_error: 1 # by default the word 'linter' will be unknown
            - name: Lint and spell-check fine.tex
              uses: ./
              with:
                  root_file: fine.tex
                  working_directory: test/
                  args: --check en --dict en.dict
                  threshold_error: 0
