name: Test on Documents

on: [push, pull_request]

jobs:
    test-on-documents:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v3
            - name: Lint fine.tex
              id: fine
              uses: ./localAction
              with:
                  root_file: fine.tex
                  working_directory: test/
                  threshold_error: 0
            - name: Assert num_warnings == 0
              if: ${{ steps.fine.outputs.num_warnings != 0 }}
              run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine.outputs.num_warnings }}"; exit 1;'
            - name: Lint bad.tex with no threshold set
              id: bad_no_threshold
              uses: ./localAction
              with:
                  root_file: bad.tex
                  working_directory: test/
            - name: Assert num_warnings > 0
              if: ${{ steps.bad_no_threshold.outputs.num_warnings <= 0 }}
              run: 'echo "::error file=test/bad.tex::num_warnings: ${{ steps.bad_no_threshold.outputs.num_warnings }}"; exit 1;'
            - name: Lint bad.tex with threshold set to known warnings
              id: bad_known_threshold
              uses: ./localAction
              with:
                  root_file: bad.tex
                  working_directory: test/
                  threshold_error: 21
            - name: Assert num_warnings <= 21
              if: ${{ steps.bad_known_threshold.outputs.num_warnings > 21 }}
              run: 'echo "::error file=test/bad.tex::num_warnings: ${{ steps.bad_known_threshold.outputs.num_warnings }}"; exit 1;'
            - name: Lint and spell-check fine.tex without dict
              id: fine_spell_check_wo_dict
              uses: ./localAction
              with:
                  root_file: fine.tex
                  working_directory: test/
                  args: --check en
                  threshold_error: 1
            - name: Assert num_warnings == 1
              if: ${{ steps.fine_spell_check_wo_dict.outputs.num_warnings != 1 }}
              run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine_spell_check_wo_dict.outputs.num_warnings }}"; exit 1;'
            - name: Lint and spell-check fine.tex with dict
              id: fine_spell_check_w_dict
              uses: ./localAction
              with:
                  root_file: fine.tex
                  working_directory: test/
                  args: --check en --dict en.dict
                  threshold_error: 0
            - name: Assert num_warnings == 0
              if: ${{ steps.fine_spell_check_w_dict.outputs.num_warnings != 0 }}
              run: 'echo "::error file=test/fine.tex::num_warnings: ${{ steps.fine_spell_check_w_dict.outputs.num_warnings }}"; exit 1;'
